module.exports = {
  RATE_BURST_WINDOW_MIN: 10,
  RATE_BURST_THRESHOLD: 8,
  ERROR_BURST_WINDOW_MIN: 10,
  ERROR_BURST_MIN_SAMPLE: 3,
  ERROR_BURST_FRACTION: 0.6,
  RARITY_THRESHOLD: 0.01,
  SESSION_VOLUME_PERCENTILE: 0.99,
  FLAG_THRESHOLD: 50,
};